### ISSUE TITLE
Allow filter of the checkbox on the checkout page 

### ISSUE THREAD

**Issue by misulicus** [easydigitaldownloads/edd-aweber#4]
https://github.com/easydigitaldownloads/edd-aweber/blob/master/includes/class-edd-newsletter.php#L131

The checkbox is hardcoded as checked so a way to filter the checkbox would be good. An option in the admin to toggle checked on or not would be even better

**Comment by pippinsplugins** [comment]
Let's do an option in the admin.

**Comment by misulicus** [comment]
Tested locally and works fine on my end

**Comment by pippinsplugins** [comment]
https://github.com/easydigitaldownloads/edd-aweber/pull/6
